
version: '3.8'

services:
  ui-backend:
    build: ./ui-backend
    ports:
      - "8000:8000"
    networks:
      - my-network

  ai-backend:
    build: ./ai-backend
    ports:
      - "8001:8001"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
